version: '3'
services:
    proxy:
        build:
            context: ./proxy
        container_name: proxy
        networks:
            mynet:
                ipv4_address: 172.29.0.2
        ports:
            - "80:80"
        working_dir: /usr/share/nginx/html
        volumes:
            - react-static:/usr/share/nginx/html

    interface_one:
        build:
            context: .
        container_name: interface_one
        networks:
            mynet:
                 ipv4_address: 172.29.0.3
        expose:
            - "8888"
        volumes:
            - ./docker/mount/interface_one/logs:/app/logs
        environment:
            - GOPATH=/go
        links:
            - redis_one
            - redis_two
            - redis_three
    
    interface_two:
        build:
            context: .
        container_name: interface_two
        networks:
            mynet:
                 ipv4_address: 172.29.0.7
        expose:
            - "8888"
        volumes:
            - ./docker/mount/interface_two/logs:/app/logs
        environment:
            - GOPATH=/go
        links:
            - redis_one
            - redis_two
            - redis_three

    redis_one:
        build:
            context: ./docker/dockerfiles/redis_one/
        container_name: redis_one
        networks:
            mynet:
                 ipv4_address: 172.29.0.4
        expose:
            - "8000"
        volumes:
            - ./docker/mount/redis_container/redis_one:/data
        
    redis_two:
        build:
            context: ./docker/dockerfiles/redis_two/
        container_name: redis_two
        networks:
            mynet:
                 ipv4_address: 172.29.0.5
        expose:
            - "8001"
        volumes:
            - ./docker/mount/redis_container/redis_two:/data
    
    redis_three:
        build:
            context: ./docker/dockerfiles/redis_three/
        container_name: redis_three
        networks:
            mynet:
                 ipv4_address: 172.29.0.6
        expose:
            - "8002"
        volumes:
            - ./docker/mount/redis_container/redis_three:/data
            
networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

volumes:
  react-static:
