package redisWrapper

const (
	FunctionExecutionTime       = "GetRedisclient 걸린 시간 %v\n"
	RedisNodeSelected           = "GetRedisClient() : Redis Node(%s) selected\n"
	FailOverVoteResult          = "Node(%s) Failover Vote result : (%d / %d)\n"
	PromotinSlaveStart          = "checkRedisFailover() : As %s failover, Master-Promotion process start \n"
	PromotingSlaveNode          = "promoteSlaveToMaster() : Slave Node(%s) is succeeeding..\n"
	SlaveAsNewMaster            = "checkRedisFailover() : %s is a new Master!\n"
	SlaveMappedToMaster         = "Redis Slave Node(%s) Mapped from Master Node(%s) Success\n"
	NodeConnectSuccess          = "Redis Node(%s) connection Success\n"
	HashSlotAssignResult        = "Node %s hash slot range %d ~ %d\n"
	HashSlotAssignStart         = "assignHashSlotMap() : Redis Node(%s) Hash slots assigning start\n"
	HashSlotAssignFinish        = "assignHashSlotMap() : Redis Node(%s) Hash slots assign finished\n"
	RefreshedMasters            = "Refresh - Current Masters : %s"
	RefreshedSlaves             = "Refresh - Current Slaves : %s"
	SlaveNodeInfo               = "RemoveSlaveFromList() : Passed @slaveNode's role : %s, address : %s"
	MasterNodeInfo              = "RemoveMasterFromList() : Passed @slaveNode's role : %s, address : %s"
	DeadRedisNodeInfo           = "Dead Redis Node info : %s %s\n"
	HashSlotRedistributeStart   = "redistruibuteHashSlot() : Hash slots of dead Redis Node(%s) will be redistributed\n"
	HashSlotRedistributeFinish  = "redistruibuteHashSlot() : Redistribution of dead Redis Node(%s)'s Hash slots finished \n"
	StartToRequestToMonitors    = "askRedisIsAliveToMonitors() : start to request to Monitor servers"
	WaitForResponseFromMonitors = "askRedisIsAliveToMonitors() : Waiting for response in channel"
	ChannelResponseFromMonitor  = "askRedisIsAliveToMonitors() : Buffered channel response : %s\n"
	RedisCheckedAlive           = "askRedisIsAliveToMonitors() : %s is said to be alive\n"
	RedisCheckedDead            = "askRedisIsAliveToMonitors() : %s is said to be dead\n"
	RequestTargetMonitor        = "requestToMonitor() : Request To : "
	ResponseFromTargetMonitor   = "requestToMonitor() : Response - is alive : "
	/* Error Log Templates */
	MasterSlaveMapNotInit    = "promoteSlaveToMaster() - Master Slave Map is not set up"
	BothMasterSlaveDead      = "promoteSlaveToMaster() : Both Master and Slave are dead"
	ConnectionFailure        = "Redis Node(%s) connection failure - %s\n"
	RedisMasterNotSetUpYet   = "Redis Master Node should be set up first"
	RedisSlaveNotSetUpYet    = "Redis Slave Node should be set up first"
	NotAnyRedisSetUpYet      = "GetRedisClientWithAddress() error : No Redis Clients set up"
	SlaveNumberMustBeLarger  = "The number of Slave Nodes should be bigger than Master's"
	NoMatchingSlaveToRemove  = "RemoveSlaveFromList() : No Matching Redis Client to Remove - %s"
	NoMatchingMasterToRemove = "RemoveMasterFromList() : No Matching Redis Client to Remove - %s"
	NoMatchingRedisToFind    = "GetRedisClientWithAddress() error : No Matching Redis Client With passed address"
	NoHashRangeIsAssigned    = "redistruibuteHashSlot() : No Hash Range is assigned to Node(%s)"
	MonitorNodesError        = "MonitorMasters() : Error - timer stopped"
	ResponseMonitorError     = "requestToMonitor() :Monitor server(IP : %s) response error : %s\n"
	NoMatchingResponseNode   = "Reuqested Redis Node Address Not Match with Response"
)
