package templates

const (
	FunctionExecutionTime       = "GetRedisclient 걸린 시간 %v\n"
	RedisNodeSelected           = "GetRedisClient() : Redis Node(%s) selected\n"
	FailOverVoteResult          = "Node(%s) Failover Vote result : (%d / %d)\n"
	PromotinSlaveStart          = "checkRedisFailover() : As %s failover, Master-Promotion process start \n"
	PromotingSlaveNode          = "promoteSlaveToMaster() : Slave Node(%s) is succeeeding..\n"
	SlaveAsNewMaster            = "checkRedisFailover() : %s is a new Master!\n"
	SlaveMappedToMaster         = "Redis Slave Node(%s) Mapped from Master Node(%s) Success\n"
	NodeConnectSuccess          = "Redis Node(%s) connection Success\n"
	HashSlotAssignResult        = "Node %s hash slot range %d ~ %d\n"
	HashSlotAssignStart         = "assignHashSlotMap() : Redis Node(%s) Hash slots assigning start\n"
	HashSlotAssignFinish        = "assignHashSlotMap() : Redis Node(%s) Hash slots assign finished\n"
	RefreshedMasters            = "Refresh - Current Masters : %s"
	RefreshedSlaves             = "Refresh - Current Slaves : %s"
	SlaveNodeInfo               = "RemoveSlaveFromList() : Passed @slaveNode's role : %s, address : %s"
	MasterNodeInfo              = "RemoveMasterFromList() : Passed @slaveNode's role : %s, address : %s"
	DeadRedisNodeInfo           = "Dead Redis Node info : %s %s\n"
	HashSlotRedistributeStart   = "redistruibuteHashSlot() : Hash slots of dead Redis Node(%s) will be redistributed\n"
	HashSlotRedistributeFinish  = "redistruibuteHashSlot() : Redistribution of dead Redis Node(%s)'s Hash slots finished \n"
	StartToRequestToMonitors    = "askRedisIsAliveToMonitors() : start to request to Monitor servers"
	WaitForResponseFromMonitors = "askRedisIsAliveToMonitors() : Waiting for response in channel"
	ChannelResponseFromMonitor  = "askRedisIsAliveToMonitors() : Buffered channel response : %s\n"
	RedisCheckedAlive           = "askRedisIsAliveToMonitors() : %s is said to be alive\n"
	RedisCheckedDead            = "askRedisIsAliveToMonitors() : %s is said to be dead\n"
	RequestTargetMonitor        = "requestToMonitor() : Request To : "
	ResponseFromTargetMonitor   = "requestToMonitor() : Response - is alive : "
)
